

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 * Servlet implementation class AccessIntraOral
 */
public class AccessIntraOral extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		PrintWriter out=response.getWriter();
		String id=request.getParameter("id");
		out.print("<html>\n"
				+ "<head>\n"
				+ "<meta charset=\"UTF-8\">\n"
				+ "	<title>Intraoral Examination</title>\n"
				+ "	<link rel=\"stylesheet\" href=\"intraoralexam_CSS.css\">\n"
				+ "</head>\n"
				+ "<style>\n"
				+ ".box {\n"
				+ "			position: relative;\n"
				+ "			display: inline-block;\n"
				+ "			width: 50px;\n"
				+ "			height: 50px;\n"
				+ "			border: 1px solid black;\n"
				+ "			text-align: center;\n"
				+ "			font-size: 20px;\n"
				+ "			margin: 5px;\n"
				+ "			padding: 0;\n"
				+ "			box-sizing: border-box;\n"
				+ "		}\n"
				+ "		.box input {\n"
				+ "			position: absolute;\n"
				+ "			top: 50%;\n"
				+ "			left: 50%;\n"
				+ "			transform: translate(-50%, -50%);\n"
				+ "			width: 80%;\n"
				+ "			height: 80%;\n"
				+ "			border: none;\n"
				+ "			text-align: center;\n"
				+ "			font-size: 14px;\n"
				+ "			box-sizing: border-box;\n"
				+ "		}\n"
				+ "		.row {\n"
				+ "			text-align: center;\n"
				+ "		}\n"
				+ "		\n"
				+ "		.label {\n"
				+ "			display: inline-block;\n"
				+ "			width: 60px;\n"
				+ "			text-align: right;\n"
				+ "			margin-right: 10px;\n"
				+ "			font-size: 12px;\n"
				+ "		}\n"
				+ "		\n"
				+ "		.label2 {\n"
				+ "			display: inline-block;\n"
				+ "			width: 60px;\n"
				+ "			text-align: left;\n"
				+ "			margin-left: 10px;\n"
				+ "			font-size: 12px;\n"
				+ "		}\n"
				+ "		\n"
				+ "		.label-permanentteeth {\n"
				+ "			display: inline-block;\n"
				+ "			width: 60px;\n"
				+ "			text-align: center;\n"
				+ "			margin-left: 10px;\n"
				+ "			font-size: 12px;\n"
				+ "		}\n"
				+ "		\n"
				+ "		textarea {\n"
				+ "  			width: 20%;\n"
				+ "  			height: 150px;\n"
				+ "  			padding: 12px 20px;\n"
				+ "  			box-sizing: border-box;\n"
				+ "  			border: 2px solid #ccc;\n"
				+ "  			border-radius: 4px;\n"
				+ " 			background-color: #f8f8f8;\n"
				+ "  			font-size: 16px;\n"
				+ " 			bottom: 20px;\n"
				+ "			left: 20px;\n"
				+ " 			position:fixed;\n"
				+ " 			resize: none;\n"
				+ " 			\n"
				+ "		}\n"
				+ "		 table {\n"
				+ "			border-collapse: collapse;\n"
				+ "			margin: auto;\n"
				+ "		}\n"
				+ "		\n"
				+ "		\n"
				+ "		th, td {\n"
				+ "			border: 1px solid black;\n"
				+ "			padding: 5px;\n"
				+ "			text-align: center;\n"
				+ "		}\n"
				+ "\n"
				+ "		th {\n"
				+ "			background-color: #eee;\n"
				+ "		}\n"
				+ "		\n"
				+ "		#save-btn {\n"
				+ "			position: fixed;\n"
				+ "			bottom: 20px;\n"
				+ "			right: 20px;\n"
				+ "			padding: 10px;\n"
				+ "			background-color: #996600;\n"
				+ "			color: white;\n"
				+ "			border: none;\n"
				+ "			border-radius: 5px;\n"
				+ "			cursor: pointer;\n"
				+ "		}\n"
				+ "		\n"
				+ "</style>\n"
				+ "<script type=\"text/javascript\">\n"
				+ "function confirm() {\n"
				+ "		alert(\"Saved Successfully!\");\n"
				+ "}\n"
				+ "</script>"
				+ "<body>\n"
				+ "	<h1 align=\"center\">Intraoral Examination</h1> <!--FIRST ROW-->\n"
				+ "	\n");
		try {
			Class.forName("com.mysql.cj.jdbc.Driver");
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/edc","root","");
			
		
		
			PreparedStatement ps = con.prepareStatement("SELECT IntraOral.Pxid, IntraOral.TopToothNo_55, IntraOral.TopToothNo_54, IntraOral.TopToothNo_53, IntraOral.TopToothNo_52, IntraOral.TopToothNo_51, IntraOral.TopToothNo_61, IntraOral.TopToothNo_62, IntraOral.TopToothNo_63, IntraOral.TopToothNo_64, IntraOral.TopToothNo_65, IntraOral.BottomToothNo_55, IntraOral.BottomToothNo_54, IntraOral.BottomToothNo_53, IntraOral.BottomToothNo_52, IntraOral.BottomToothNo_51, IntraOral.BottomToothNo_61, IntraOral.BottomToothNo_62, IntraOral.BottomToothNo_63, IntraOral.BottomToothNo_64, IntraOral.BottomToothNo_65, IntraOral.TopToothNo_18, IntraOral.TopToothNo_17, IntraOral.TopToothNo_16, IntraOral.TopToothNo_15, IntraOral.TopToothNo_14, IntraOral.TopToothNo_13, IntraOral.TopToothNo_12, IntraOral.TopToothNo_11, IntraOral.TopToothNo_21, IntraOral.TopToothNo_22, IntraOral.TopToothNo_23, IntraOral.TopToothNo_24, IntraOral.TopToothNo_25, IntraOral.TopToothNo_26, IntraOral.TopToothNo_27, IntraOral.TopToothNo_28, IntraOral.BottomToothNo_18, IntraOral.BottomToothNo_17, IntraOral.BottomToothNo_16, IntraOral.BottomToothNo_15, IntraOral.BottomToothNo_14, IntraOral.BottomToothNo_13, IntraOral.BottomToothNo_12, IntraOral.BottomToothNo_11, IntraOral.BottomToothNo_21, IntraOral.BottomToothNo_22, IntraOral.BottomToothNo_23, IntraOral.BottomToothNo_24, IntraOral.BottomToothNo_25, IntraOral.BottomToothNo_26, IntraOral.BottomToothNo_27, IntraOral.BottomToothNo_28, IntraOral.TopToothNo_48, IntraOral.TopToothNo_47, IntraOral.TopToothNo_46, IntraOral.TopToothNo_45, IntraOral.TopToothNo_44, IntraOral.TopToothNo_43, IntraOral.TopToothNo_42, IntraOral.TopToothNo_41, IntraOral.TopToothNo_31, IntraOral.TopToothNo_32, IntraOral.TopToothNo_33, IntraOral.TopToothNo_34, IntraOral.TopToothNo_35, IntraOral.TopToothNo_36, IntraOral.TopToothNo_37, IntraOral.TopToothNo_38, IntraOral.BottomToothNo_48, IntraOral.BottomToothNo_47, IntraOral.BottomToothNo_46, IntraOral.BottomToothNo_45, IntraOral.BottomToothNo_44, IntraOral.BottomToothNo_43, IntraOral.BottomToothNo_42, IntraOral.BottomToothNo_41, IntraOral.BottomToothNo_31, IntraOral.BottomToothNo_32, IntraOral.BottomToothNo_33, IntraOral.BottomToothNo_34, IntraOral.BottomToothNo_35, IntraOral.BottomToothNo_36, IntraOral.BottomToothNo_37, IntraOral.BottomToothNo_38, IntraOral.TopToothNo_85, IntraOral.TopToothNo_84, IntraOral.TopToothNo_83, IntraOral.TopToothNo_82, IntraOral.TopToothNo_81, IntraOral.TopToothNo_71, IntraOral.TopToothNo_72, IntraOral.TopToothNo_73, IntraOral.TopToothNo_74, IntraOral.TopToothNo_75, IntraOral.BottomToothNo_85, IntraOral.BottomToothNo_84, IntraOral.BottomToothNo_83, IntraOral.BottomToothNo_82, IntraOral.BottomToothNo_81, IntraOral.BottomToothNo_71, IntraOral.BottomToothNo_72, IntraOral.BottomToothNo_73, IntraOral.BottomToothNo_74, IntraOral.BottomToothNo_75, IntraOral.notes FROM edc.IntraOral WHERE Pxid = ?");
			
			ps.setString(1, id);
			
			ResultSet rs = ps.executeQuery();
			
			while(rs.next()) {
				
				out.print("<form action=\"UpdateOralServlet\" method=\"post\">\n"
						+ "<input type=\"hidden\" name=\"id\" value="+rs.getInt(1)+">\n"
						+ "<div class=\"row\">\n"
						+ "	<div class=\"label\">STATUS</div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box1\" value="+rs.getString(2)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box2\" value="+rs.getString(3)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box3\" value="+rs.getString(4)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box4\" value="+rs.getString(5)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box5\" value="+rs.getString(6)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box6\" value="+rs.getString(7)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box7\" value="+rs.getString(8)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box8\" value="+rs.getString(9)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box9\" value="+rs.getString(10)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box10\" value="+rs.getString(11)+"></div>\n"
						+ "		<div class=\"label2\"></div>\n"
						+ "	</div>\n"
						+ "	\n"
						+ "	<div class=\"row\">\n"
						+ "	<div class=\"label\">RIGHT</div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box11\" value="+rs.getString(12)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box12\" value="+rs.getString(13)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box13\" value="+rs.getString(14)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box14\" value="+rs.getString(15)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box15\" value="+rs.getString(16)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box16\" value="+rs.getString(17)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box17\" value="+rs.getString(18)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box18\" value="+rs.getString(19)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box19\" value="+rs.getString(20)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box20\" value="+rs.getString(21)+"></div>\n"
						+ "		<div class=\"label2\">LEFT</div>\n"
						+ "	</div>\n"
						+ "	<div class=\"row\">\n"
						+ "	<div class=\"label\">TEMPORARY TEETH</div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box21\" value="+rs.getString(22)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box22\" value="+rs.getString(23)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box23\" value="+rs.getString(24)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box24\" value="+rs.getString(25)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box25\" value="+rs.getString(26)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box26\" value="+rs.getString(27)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box27\" value="+rs.getString(28)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box28\" value="+rs.getString(29)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box29\" value="+rs.getString(30)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box30\" value="+rs.getString(31)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box31\" value="+rs.getString(32)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box32\" value="+rs.getString(33)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box33\" value="+rs.getString(34)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box34\" value="+rs.getString(35)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box35\" value="+rs.getString(36)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box36\" value="+rs.getString(37)+"></div>\n"
						+ "		<div class=\"label2\"></div>\n"
						+ "	</div>\n"
						+ "	<div class=\"row\">\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box37\" value="+rs.getString(38)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box38\" value="+rs.getString(39)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box39\" value="+rs.getString(40)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box40\" value="+rs.getString(41)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box41\" value="+rs.getString(42)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box42\" value="+rs.getString(43)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box43\" value="+rs.getString(44)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box44\" value="+rs.getString(45)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box45\" value="+rs.getString(46)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box46\" value="+rs.getString(47)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box47\" value="+rs.getString(48)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box48\" value="+rs.getString(49)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box49\" value="+rs.getString(50)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box50\" value="+rs.getString(51)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box51\" value="+rs.getString(52)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box52\" value="+rs.getString(53)+"></div>\n"
						+ "		\n"
						+ "	<div class=\"row\">\n"
						+ "	<div class=\"label-permanentteeth\">PERMANENT TEETH</div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	<div class=\"label-permanentteeth\"></div>\n"
						+ "	\n"
						+ "	</div>\n"
						+ "	</div>\n"
						+ "	<div class=\"row\">\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box53\" value="+rs.getString(54)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box54\" value="+rs.getString(55)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box55\" value="+rs.getString(56)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box56\" value="+rs.getString(57)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box57\" value="+rs.getString(58)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box58\" value="+rs.getString(59)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box59\" value="+rs.getString(60)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box60\" value="+rs.getString(61)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box61\" value="+rs.getString(62)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box62\" value="+rs.getString(63)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box63\" value="+rs.getString(64)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box64\" value="+rs.getString(65)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box65\" value="+rs.getString(66)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box66\" value="+rs.getString(67)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box67\" value="+rs.getString(68)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box68\" value="+rs.getString(69)+"></div>\n"
						+ "	</div>\n"
						+ "\n"
						+ "	<div class=\"row\">\n"
						+ "	<div class=\"label\">TEMPORARY TEETH</div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box69\" value="+rs.getString(70)+"></div> \n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box70\" value="+rs.getString(71)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box71\" value="+rs.getString(72)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box72\" value="+rs.getString(73)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box73\" value="+rs.getString(74)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box74\" value="+rs.getString(75)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box75\" value="+rs.getString(76)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box76\" value="+rs.getString(77)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box77\" value="+rs.getString(78)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box78\" value="+rs.getString(79)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box79\" value="+rs.getString(80)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box80\" value="+rs.getString(81)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box81\" value="+rs.getString(82)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box82\" value="+rs.getString(83)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box83\" value="+rs.getString(84)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box84\" value="+rs.getString(85)+"></div>\n"
						+ "		<div class=\"label\"></div>\n"
						+ "	</div>\n"
						+ "	\n"
						+ "	<div class=\"row\">\n"
						+ "	<div class=\"label\">STATUS</div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box85\" value="+rs.getString(86)+"></div> \n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box86\" value="+rs.getString(87)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box87\" value="+rs.getString(88)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box88\" value="+rs.getString(89)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box89\" value="+rs.getString(90)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box90\" value="+rs.getString(91)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box91\" value="+rs.getString(92)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box92\" value="+rs.getString(93)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box93\" value="+rs.getString(94)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box94\" value="+rs.getString(95)+"></div>\n"
						+ "		<div class=\"label\"></div>\n"
						+ "	</div>\n"
						+ "	\n"
						+ "	<div class=\"row\">\n"
						+ "	<div class=\"label\">RIGHT</div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box95\" value="+rs.getString(96)+"></div> \n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box96\" value="+rs.getString(97)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box97\" value="+rs.getString(98)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box98\" value="+rs.getString(99)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box99\" value="+rs.getString(100)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box100\" value="+rs.getString(101)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box101\" value="+rs.getString(102)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box102\" value="+rs.getString(103)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box103\" value="+rs.getString(104)+"></div>\n"
						+ "		<div class=\"box\"><input type=\"text\" name=\"box104\" value="+rs.getString(105)+"></div>\n"
						+ "	<div class=\"label2\">LEFT</div>\n"
						+ "	</div>	\n"
						+ "	\n"
						+ "	\n"
						+ "	\n"
						+ "	<div class=\"guide\">\n"
						+ "	<table>\n"
						+ "		<tr>\n"
						+ "			<th>Condition</th>\n"
						+ "			<th>Restorations & Prosthetics</th>\n"
						+ "			<th>Surgery</th>\n"
						+ "		</tr>\n"
						+ "		<tr>\n"
						+ "			<td># - Present Teeth</td>\n"
						+ "			<td>Am - Amaigam Filling</td>\n"
						+ "			<td>X - Extraction due to Caries</td>\n"
						+ "		</tr>\n"
						+ "		<tr>\n"
						+ "			<td>D - Decayed(Caries Indicated for Filling)</td>\n"
						+ "			<td>Co - Composite Filling</td>\n"
						+ "			<td>XO - Extraction due to Other Causes</td>\n"
						+ "		</tr>\n"
						+ "		<tr>\n"
						+ "			<td>M - Missing due to Caries</td>\n"
						+ "			<td>JC - Jacket Crown</td>\n"
						+ "			<td></td>\n"
						+ "		</tr>\n"
						+ "		<tr>\n"
						+ "			<td>MO - Missing due to Other Causes</td>\n"
						+ "			<td>Ab - Abutment</td>\n"
						+ "			<td></td>\n"
						+ "		</tr>\n"
						+ "		<tr>\n"
						+ "			<td>Im - Impacted Tooth</td>\n"
						+ "			<td>Att - Attachment</td>\n"
						+ "			<td></td>\n"
						+ "		</tr>\n"
						+ "		<tr>\n"
						+ "			<td>Sp - Supernumerary Tooth</td>\n"
						+ "			<td>P - Pontic</td>\n"
						+ "			<td></td>\n"
						+ "		</tr>\n"
						+ "		<tr>\n"
						+ "			<td>Rf - Root Fragment</td>\n"
						+ "			<td>In - Inlay</td>\n"
						+ "			<td></td>\n"
						+ "		</tr>\n"
						+ "		<tr>\n"
						+ "			<td>Un - Unerupted</td>\n"
						+ "			<td>Imp - Implant</td>\n"
						+ "			<td></td>\n"
						+ "		</tr>\n"
						+ "		<tr>\n"
						+ "			<td></td>\n"
						+ "			<td>S - Sealants</td>\n"
						+ "			<td></td>\n"
						+ "		</tr>\n"
						+ "		<tr>\n"
						+ "			<td></td>\n"
						+ "			<td>Rm - Removable Denture</td>\n"
						+ "			<td></td>\n"
						+ "		</tr>\n"
						+ "	</table>\n"
						+ "	</div>\n"
						+ "	\n"
						+ "	<div class=\"note\">\n"
						+ "		<textarea name=\"note\" placeholder=\"enter your notes here\">"+rs.getString(106)+"</textarea>\n"
						+ "	</div>\n"
						+ "<button id=\"save-btn\" onclick=\"confirm()\">Save Patient Record</button>\n"
						+ "\n"
						+ "</form>"
						+ "	\n"
						+ "</body>\n"
						+ "</html>");
				
			
			}
			
			
		}catch(Exception p) {
			System.out.println(p);
		}
		
		//add manage treatment record
		
		out.print("</table>");
		
		out.print( "</body>"
				+ "</html>");
	
				
	}

}
